#!/bin/bash

# we have to unset this for Darwin since it will screw up KDE's dynamic-loading
unset DYLD_FORCE_FLAT_NAMESPACE

# This script can be used to source other shell scripts, initialize
# the environment etc.

env > /tmp/startplasma-${USER}.env
if [ -f /etc/mer-release ]; then
    ck-launch-session startplasma.bin 2>&1 | tee /tmp/startplasma-${USER}.log
else
    startplasma.bin 2>&1 | tee /tmp/startplasma-${USER}.log
fi

