#!/bin/bash

#make sure org.kde.plasma.core can be imported
export QML_IMPORT_PATH=/usr/lib/kde4/imports/

#enable maliit plugin
export QT_IM_MODULE=Maliit

env > /tmp/startactive-${USER}.env
if [ -f /etc/mer-release ]; then
    ck-launch-session startactive.bin 2>&1 | tee /tmp/startactive-${USER}.log
else
    startactive.bin 2>&1 | tee /tmp/startactive-${USER}.log
fi

